version: '3'
services:
  hyperion-ts:
    image: hyperion-ts
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_CONFIG_DIR=./dist/main/config
      - SERVER_PORT=8080
      - HYPERION_ADDRESS=black-pearl.local
      - HYPERION_PORT=19444
      - HYPERION_PRIORITY=1
    command: "node ."