version: '3'
services:
  hyperion-ts:
    image: hyperion-ts
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_CONFIG_DIR=/usr/app/dist/config
      - SERVER_PORT=8080
      - HYPERION_ADDRESS=192.168.86.30
      - HYPERION_PORT=19444
      - HYPERION_PRIORITY=1000